from django.urls import path
from . import views
urlpatterns = [
	path("", views.index, name="index"),
    path("info/", views.info, name="info"), 
    path('test_accesare/', views.test_accesare),
    path("exemplu/", views.afis_template, name="exemplu"),
    path("log/", views.log, name="log"),
    path('produse/', views.lista_produse, name='lista_produse'),
    path("despre/", views.despre, name="despre"),
    path("cos_virtual/", views.in_lucru, name="cos_virtual"),
    path("in_lucru/", views.in_lucru, name="in_lucru"),
    path("baza/", views.baza, name="baza"),
    path("comenzi/", views.in_lucru, name="comenzi"),
    path("social/", views.in_lucru, name="social"),
    path("produse/<int:produs_id>/", views.detalii_produs, name="Detalii_produs"),
    path('categorii/<str:nume_categorie>/', views.produse_dupa_categorie, name='produse_dupa_categorie'),
    path("product_list_view/", views.product_list_view, name="product_list_view"),
    path("contact/", views.contact_view, name="contact_page"),
    #path('adaugare/', views.introducere_produs, name='adaugare_produs'),
    path('adaugare_produs/', views.introducere_produs, name='adaugare'),
    path('inregistrare/', views.register_view, name='register'),
    path('login/', views.custom_login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profil/', views.pagina_profil_view, name='profil'),
    path('schimba_parola/', views.change_password_view, name='schimbare_parola'),
    path('confirma_mail/<str:cod>/', views.confirma_email_view, name='confirma_mail'),
]