# Generated by Django 5.2.7 on 2025-10-22 13:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazin_de_muzica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100, unique=True)),
                ('gen_muzical', models.CharField(max_length=100)),
                ('ani_activitate', models.IntegerField(blank=True, null=True)),
                ('tip_activitate', models.CharField(choices=[('S', 'Solo'), ('B', 'Band'), ('D', 'Duo')], default='S', max_length=1)),
                ('data_adaugare', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Campanie_Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_campanie', models.CharField(max_length=100, unique=True)),
                ('data_inceput', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_sfarsit', models.DateField()),
                ('reducere', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tip_campanie', models.CharField(choices=[('S', 'Seasonal'), ('F', 'Flash'), ('B', 'BlackFriday')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_categorie', models.CharField(max_length=100, unique=True)),
                ('data_creare', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_actualizare', models.DateTimeField(auto_now=True)),
                ('tip_categorie', models.CharField(choices=[('C', 'CD-uri'), ('K', 'Casete'), ('V', 'Vinyl')], default='C', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.TextField()),
                ('pret', models.PositiveIntegerField(default=0)),
                ('stoc', models.FloatField(default=0.0)),
                ('data_adaugare', models.DateTimeField(default=django.utils.timezone.now)),
                ('campanii', models.ManyToManyField(blank=True, to='Magazin_de_muzica.campanie_promo')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Magazin_de_muzica.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Produs_Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_artist', models.CharField(max_length=300)),
                ('colaborare_speciala', models.CharField(blank=True, max_length=200, null=True)),
                ('descriere', models.TextField(blank=True)),
                ('tip_rol', models.CharField(choices=[('S', 'Solist'), ('B', 'Background'), ('P', 'Producer')], default='S', max_length=1)),
                ('data_adaugare', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Locatie',
        ),
        migrations.DeleteModel(
            name='Organizator',
        ),
    ]
