# Generated by Django 5.2.7 on 2025-10-22 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazin_de_muzica', '0002_artist_campanie_promo_categorie_produs_produs_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs_artist',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Magazin_de_muzica.artist'),
        ),
        migrations.AddField(
            model_name='produs_artist',
            name='produs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Magazin_de_muzica.produs'),
        ),
        migrations.AddConstraint(
            model_name='produs_artist',
            constraint=models.UniqueConstraint(fields=('produs', 'artist'), name='unique_produs_artist'),
        ),
    ]
