# Generated by Django 5.2.7 on 2025-10-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazin_de_muzica', '0003_produs_artist_artist_produs_artist_produs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='tip_categorie',
            field=models.CharField(choices=[('C', 'CD-uri'), ('K', 'Casete'), ('V', 'Vinyl'), ('M', 'Merch')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='produs_artist',
            name='rol_artist',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
