# Generated by Django 5.2.7 on 2025-11-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazin_de_muzica', '0004_alter_categorie_tip_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='imagini/'),
        ),
    ]
