# Generated by Django 5.2.7 on 2025-11-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazin_de_muzica', '0005_produs_imagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='produse/'),
        ),
    ]
