# Generated by Django 5.2.7 on 2025-11-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazin_de_muzica', '0009_alter_produs_imagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='culoare',
            field=models.CharField(default='#6A5ACD', max_length=20),
        ),
    ]
