# Generated by Django 5.2.7 on 2025-11-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazin_de_muzica', '0010_categorie_culoare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='pret',
            field=models.PositiveIntegerField(),
        ),
    ]
