# Generated by Django 5.2.7 on 2025-11-23 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazin_de_muzica', '0011_alter_produs_pret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=15)),
                ('tara', models.CharField(blank=True, max_length=100)),
                ('judet', models.CharField(blank=True, max_length=100)),
                ('oras', models.CharField(blank=True, max_length=100)),
                ('strada', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
