# Generated by Django 5.2.7 on 2025-11-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazin_de_muzica', '0012_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='cod',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='email_confirmat',
            field=models.BooleanField(default=False, max_length=255),
        ),
    ]
