# Generated by Django 5.2.7 on 2025-11-29 09:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazin_de_muzica', '0013_profil_cod_profil_email_confirmat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_comanda', models.DateTimeField(default=django.utils.timezone.now)),
                ('metoda', models.CharField(choices=[('card', 'Card Online'), ('ramburs', 'Ramburs la livrare'), ('transfer', 'Transfer Bancar')], default='ramburs', max_length=20)),
                ('status_comanda', models.CharField(choices=[('plasata', 'Plasată'), ('procesare', 'În procesare'), ('expediata', 'Expediată'), ('finalizata', 'Finalizată'), ('anulata', 'Anulată')], default='plasata', max_length=20)),
                ('status_livrare', models.CharField(blank=True, max_length=50, null=True)),
                ('data_livrare', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetaliiComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.PositiveIntegerField(default=1)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalii', to='Magazin_de_muzica.comanda')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Magazin_de_muzica.produs')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriere', models.TextField()),
                ('data_publicarii', models.DateTimeField(default=django.utils.timezone.now)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewuri', to='Magazin_de_muzica.produs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoare', models.PositiveIntegerField()),
                ('tip_rating', models.CharField(choices=[('produs', 'Calitate Produs'), ('livrare', 'Experiență Livrare'), ('pret', 'Raport Calitate/Preț')], default='produs', max_length=20)),
                ('data_rating', models.DateTimeField(default=django.utils.timezone.now)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratinguri', to='Magazin_de_muzica.produs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('produs', 'user', 'tip_rating'), name='unique_rating_user_produs')],
            },
        ),
    ]
