# Generated by Django 5.2.7 on 2025-11-29 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazin_de_muzica', '0015_vizualizare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.TextField()),
                ('data_creare', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_expirare', models.DateTimeField()),
                ('procent_reducere', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subiect_email', models.CharField(help_text='Subiectul care va apărea în mail', max_length=255)),
            ],
        ),
    ]
