# Generated by Django 5.2.7 on 2025-11-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazin_de_muzica', '0016_promotii'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotii',
            name='categorii',
            field=models.ManyToManyField(help_text='Categorii la care se aplică promoția', to='Magazin_de_muzica.categorie'),
        ),
    ]
