# Generated by Django 5.2.7 on 2025-12-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazin_de_muzica', '0017_promotii_categorii'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='blocat',
            field=models.BooleanField(default=False),
        ),
    ]
